### ISSUE TITLE
I want to create/build an api to parse ppt and pptx

### ISSUE THREAD

**Issue by lucasverra** [groupdocs-free-consulting/projects#1]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to GroupDocs APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.groupdocs.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

Hello, im trying to build and cloud endpoint where i would POST a pptx file and receive text srting. 
bassically doing the same as https://products.groupdocs.app/parser/pptx, but 
 - serverless and output would be a JSON 

< which platform you're working on -- operating system, development environment etc.>

serverless so python java javascript, i do not manage servers ever :) 

<attach input documents>

[WEEM DATA ENG-VERRA(1).pptx](https://github.com/groupdocs-free-consulting/projects/files/4416838/WEEM.DATA.ENG-VERRA.1.pptx)

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

super simple i guess if i manage to get the code or an api endpoint. Maybe you already have that service 

my ideal workflow is 

POST pptx to api => serverless api do the parsing => response json with all the texts

Can you help me ?

**Comment by shahzad-latif** [comment]
@lucasverra 

Thanks for your request and sorry for late reply. We'll check your requirements in detail and then update you with our findings.

**Comment by tilalahmad** [comment]
@lucasverra 

We have checked your requirements and pleased to inform you that you can use GroupDocs.Parser Cloud API for the purpose. It is a document data extraction REST API that support over 50 common document types, based on [GroupDocs.Parser on premise API](https://products.groupdocs.com/parser). 

You can use GroupDocs.Parser Cloud API with any language or platform that supports REST. We also provide SDKs for different platforms along with working example on [GitHub Repository](https://github.com/groupdocs-parser-cloud?tab=repositories), so you can use GroupDocs.Parser Cloud REST APIs in your applications quickly and easily, without any learning curve. Currently .NET and Java SDKs are published. We will publish SDKs for other popular languages in near future.

> serverless so python java javascript

For your requirement, you can use GroupDocs.Parser Cloud SDK for Java from [GitHub](https://github.com/groupdocs-parser-cloud/groupdocs-parser-cloud-java) or [Maven](https://repository.groupdocs.cloud/webapp/#/artifacts/browse/tree/General/repo/com/groupdocs/groupdocs-parser-cloud). If you want to use GroupDocs.Parser Cloud API in Python, then you may use it via some supported REST Client (e.g. requests). However, we will launch SDK for Python in near future as well. If you allow, I can create a post in GroupDocs Cloud forum on your behalf, so you will get an email notification as soon as GroupDocs.Parser Cloud SDK for Pyhton is published.

Here is GroupDocs.Parser Cloud SDK for Java code sample for posting PPTX to Cloud storage and extract text.  Please check [GroupDocs.Parser Cloud documentation](https://wiki.groupdocs.cloud/parsercloud/) for more details. You can quickly explore the [GroupDocs.Parser REST API](https://apireference.groupdocs.cloud/parser/) in your browser and post query in [GroupDocs.Parser Cloud forum](https://forum.groupdocs.cloud/c/parser) for any assistance.

Upload File to Cloud Storage:

```
// Get your AppSID and AppKey at https://dashboard.groupdocs.cloud (free
// registration is required).
Configuration configuration = new Configuration(appSid, appKey);

FileApi fileApi = new FileApi(configuration);

try {
	// Path where to upload including filename and extension
	String path = "Temp/WEEM DATA ENG-VERRA 1.pptx";
	// File to upload
	File file = new File("C:/Temp/WEEM DATA ENG-VERRA 1.pptx");
	// Storage name, GroupDocs Cloud is default storage
	String storage = null;

	UploadFileRequest request = new UploadFileRequest(path, file, storage);
	fileApi.uploadFile(request);
} catch (ApiException e) {
	System.err.println("Failed to upuload file");
	e.printStackTrace();
}

```

Extract Text:

```
// Get your AppSID and AppKey at https://dashboard.groupdocs.cloud (free
// registration is required).
Configuration configuration = new Configuration(appSid, appKey);

ParseApi parseApi = new ParseApi(configuration);
try {
	TextOptions options = new TextOptions();
	FileInfo fileInfo = new FileInfo();
	fileInfo.setFilePath("Temp/WEEM DATA ENG-VERRA 1.pptx");
	options.setFileInfo(fileInfo);
	TextRequest request = new TextRequest(options);

	// Parse Text
	TextResult result = parseApi.text(request);
	System.out.println(result.getText());

} catch (ApiException e) {
	System.err.println("Text Parsing Failed");
	e.printStackTrace();
}
```

Result:
```
1
EXPERTISES


SOFT SKILLS


Proactif
Structuré
Organisé
Pragmatique
Créatif
Innovant
33 ans
9 ans d’expérience professionnelle
FORMATION
2010-2011 : Centrale Paris
Master 2 : Modélisation et systèmes d'innovations

SECTEURS
Tourisme
Corporate Innovation
Transport
Automobile
E-Learning
Retail
Systèmes d’informations
Excel automation (sheetjs)
Cloud Architecture
Applications web - API
Data Analysis (Python/SQL)
Product Management
API integrations
HTML / CSS / JS / UX Design
EXPERIENCE PROFESSIONNELLE

Depuis 2019 : Consultant indépendant

2017-2019 : Universal Voucher, Fondateur SaaS web marketing opérationnel, backoffice avec reportings automatisés

2015-2016 : 360Learning.com, Acquisition & CRM BI Manager, implémentation Salesforce + reporting automatisés. Acquisition client via marketing digital
2012-2015 : Renault marketing, Leads & CRM. Création des campagnes emailing fidélisation poste vente
2011  : Bouygues Construction, Recherche opérationnelle. Mission corporate knowledge Management
Lucas VERRA
2
EXEMPLES DE MISSIONS RÉALISÉES
Automobile/ CRM
Manager Performance Marketing CMDM,  Renault (24 mois) : Cadrage et suivi de 2 projets majeurs. Innover et manager systèmes d'informations prospect/client pour accroître les taux de conquête et fidélisation. Création des campagnes multicanales et suivi des KPI business marketing digital (réductions cost per lead 2X en utilisant CRM data dans plateforme ads Facebook). Pilotage des différentes solutions IT/CMDM CRM pour le groupe.

-  Lead acquisition, 360Learning (8 mois) : Cadrage et préparation des campagnes d'acquisition : tester, lancer et scaler des campagnes sur les différents canaux (LK / FB / TT / Retargeting / Display / Email). Mise en place d’un reporting selon le  besoin des exécutifs en termes de données et KPI souhaités. Pilotage de la migration vers CRM Salesforce.
Transport/ gestion de projet
Implémentation d'un workflow dédommagement, Air France (12 mois) : définition d’un nouveau procédé client en collaboration avec l'innovation passager,  les systèmes d’information et webservices “traffic perturbé”. Coupons digitalisés avec les partenaires Food&Beverage en aéroport.
Refonte site e-commerce pour maroquinerie de luxe à Paris (6 mois): diagnostic stratégique – analyse web. Collaboration avec équipes internes multidisciplinaires pour le design graphique/maquettage de plusieurs pages dont la home. Reporting via backoffice.
Design des spécifications cible pour MVP web app mobile (3 mois), Agrobourse : définitions technico/fonctionnelles en lien étroit avec les membres du comité de direction, mise en production du module « transporteurs » et intégration des API avec la DSI. Implémentation des tableaux de bord dynamique à partir de ces données d’utilisation (D3.js)
Implémentation système de suivi e-couponing unique via emailing partenariat (4 mois), Bouygues Tel: Support à l’équipe « développement commercial local » pour la mise en production d’un système d’acquisition client en passant par des partenariats en collectivités locales (BDE,CE, Associations).


Lucas VERRA


```

**Comment by shahzad-latif** [comment]
@lucasverra 

You can also download the sample project from the following link and also check the details of the project: https://github.com/groupdocs-free-consulting/Extract-Text-from-Microsoft-PowerPoint-Presentation-using-JAVA-SDK-of-GroupDocs.Parser-REST-API
