### ISSUE TITLE
how i connect this docx file edit functionality in my project angular

### ISSUE THREAD

**Issue by greensky-code** [groupdocs-free-consulting/projects#10]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to GroupDocs APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.groupdocs.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by atirtahirgroupdocs** [comment]
@greensky-code 

GroupDocs.Editor API allows you to edit most popular document [formats](https://docs.groupdocs.com/editor/net/supported-document-formats/) using 3rd party front-end WYSIWYG HTML-editors without any additional applications. 
Please note that the API is UI-Agnostic, you can integrate it in any .NET or Java applications. Please share following details and we'll assist you accordingly:

* Are you looking for a [.NET](https://products.groupdocs.com/editor/net) or [Java](https://products.groupdocs.com/editor/java) variant of the API
* Your existing project details (e.g. framework, development environment)

**Comment by greensky-code** [comment]
Hello i am using angular and node js application how can implement document edit functionally

**Comment by tilalahmad** [comment]
@greensky-code 

GroupDocs.Editor Cloud API allows you to edit a wide range of documents that includes Word Processing documents without depending on MS Office or Open Office with any 3rd-party front-end WYSIWYG editor. The editor should be compatible with HTML documents.
In your scenario, you can use GroupDocs.Editor Cloud SDK for Node.js to convert Word Processing documents to HTML and edit with some HTML/WYSIWYG editor. The exact workflow will be like as follows:

- Upload input document into cloud storage
- Load the document into editable representation in the cloud storage (HTML file and resources)
- Download HTML document (and resources, if needed) from storage
- Edit HTML document at client side using some programming language or 3rd-party front-end editor
- Upload HTML document back into the storage
- Save the edited document into WordProcessing format in the storage
- Download saved document 

Please find sample Node.js example and follow these steps to proceed:

- Extract the downloaded project
- Edit RunExamples.js and put appSid and appKey, obtained from https://dashboard.groupdocs.cloud there
- Execute "npm install" command in root directory
- Execute "npm update" command in root directory
- Run examples using "npm run-script start" command

[EditWordProcessingDocument.zip](https://github.com/groupdocs-free-consulting/projects/files/5403478/EditWordProcessingDocument.zip)

**Comment by greensky-code** [comment]
How to integrate Groupdocs viewer in node and View the document in Angular
