### ISSUE TITLE
Question Document Viewer: Are there any events available which would help me track the time spent on each page by a user?

### ISSUE THREAD

**Issue by elchico-git** [groupdocs-free-consulting/projects#12]
Are there any events available which would help me track the time spent on each page by a user?

**Comment by atirtahirgroupdocs** [comment]
@elchico-git 
Please always post back-end API related queries on free support [forum](http://forum.groupdocs.com/). A thread is created on your behalf and answered on [forum](https://forum.groupdocs.com/t/question-document-viewer-are-there-any-events-available-which-would-help-me-track-the-time-spent-on-each-page-by-a-user/9042/2).
