### ISSUE TITLE
Free Online document annotation does not show comments

### ISSUE THREAD

**Issue by lubazlatin** [groupdocs-free-consulting/projects#13]
Good evening,
We added comments to the pdf file, saved them and downloaded the output file
in "Free Online document annotation" (https://docs.groupdocs.cloud/annotation/rendering-documents/) .
When the output downloaded pdf file was opened in "Free Online document annotation" (https://docs.groupdocs.cloud/annotation/rendering-documents/) , the comments disappeared.
It happens with all files.

**Comment by atirtahir** [comment]
@lubazlatin 

This topic is addressed [here](https://github.com/groupdocs-free-consulting/projects/issues/14).

**Comment by atirtahirgroupdocs** [comment]
This topic is addressed [here](https://github.com/groupdocs-free-consulting/projects/issues/14).
