### ISSUE TITLE
fff

### ISSUE THREAD

**Issue by lubazlatin** [groupdocs-free-consulting/projects#14]
We added comments to the pdf, saved them and downloaded the file with "Free online document annotation"(https://products.groupdocs.app/annotation/total), when we opened the output downloaded file with "Free online document annotation" the comments disappeared.

**Comment by lubazlatin** [comment]
We added comments to the pdf, saved them and downloaded the file with "Free online document annotation"(https://products.groupdocs.app/annotation/total), when we opened the output downloaded file with "Free online document annotation" the comments disappeared.

**Comment by atirtahirgroupdocs** [comment]
@lubazlatin 

We couldn't reproduce this issue at our end using sample PDF. When you upload a PDF file, add an annotation and write a comment, you have to press the save icon. Please have a look at the following screenshot:

![screenshot PNG](https://user-images.githubusercontent.com/15940608/104631441-102b9a00-56be-11eb-97a4-654865092050.png)
We're attaching the resultant PDF and it shows the comment that was added using the web application. 
[Annotated sample.pdf](https://github.com/groupdocs-free-consulting/projects/files/5816226/Annotated.sample.pdf)
Please always post free apps related issue on app support [forum](http://forum.groupdocs.app/). After saving the comment, if you still face the same issue, please create a thread on app support forum and share the problematic PDF with us.
