### ISSUE TITLE
Issues with PDF to Word Conversion using Rest API

### ISSUE THREAD

**Issue by vijayiner** [groupdocs-free-consulting/projects#15]
Dear Team,

I have using groupdocs to convert the PFT to word and it is working but, it is editable for some pdf... Is it another way to troubleshoot this...

**Comment by tilalahmad** [comment]
@vijayiner 

We will appreciate it if you please share your input and output documents along with the expected output document. It will help us to understand your issue exactly and address it.

**Comment by shahzad-latif** [comment]
@vijayiner 

Please note that for such kind of issues and queries we have dedicated [free support forums](https://forum.groupdocs.cloud/). Please post such requests in our free support forums, so our team can help and guide you appropriately and in a timely manner. This space is reserved for free consulting projects. So the best place to get quick support and help is our free support forums. I hope you understand. Thanks.
