### ISSUE TITLE
PDF comaparison not working as expected

### ISSUE THREAD

**Issue by poonamBattulwar** [groupdocs-free-consulting/projects#16]
I tried to compare two pdf files with the trial license which was provided. however, its not spotting the difference texts. we are considering this tool for our PDF file comparisons. we need some support around comparing these pdf files. would appreciate a working session/call

**Comment by atirtahirgroupdocs** [comment]
@poonamBattulwar 
Please share following details and we'll investigate this scenario:

- API variant (e.g. [Java or .NET](https://products.groupdocs.com/comparison)) and [version](https://downloads.groupdocs.com/comparison) (e.g. 21.2, 21.3) that you are using 
- Sample code 
- Problematic files and the output PDF

**Comment by poonamBattulwar** [comment]
Hi atirtahirgroupdocs,

Please find the details below,

- API variant (e.g. Java or .NET) and version (e.g. 21.2, 21.3) that you are using
.NET
- Sample code
string outputDirectory = Constants.GetOutputDirectoryPath();
            string outputFileName = Path.Combine(outputDirectory, Constants.RESULT_PDF);

            using (Comparer comparer = new Comparer(Constants.SOURCE_PDF))
            {
                comparer.Add(Constants.TARGET_PDF);
                comparer.Compare(outputFileName);
            }

- Problematic files and the output PDF

[Sample1.pdf](https://github.com/groupdocs-free-consulting/projects/files/6391123/Sample1.pdf)
[Sample2.pdf](https://github.com/groupdocs-free-consulting/projects/files/6391124/Sample2.pdf)

[result.pdf](https://github.com/groupdocs-free-consulting/projects/files/6391155/result.pdf)
Can we connect over a call to resolve this issue.

Regards,
Poonam

**Comment by atirtahirgroupdocs** [comment]
@poonamBattulwar 

You are getting such an output because you are evaluating the API in trial mode (without applying a license). We are getting this  
[output.pdf](https://github.com/groupdocs-free-consulting/projects/files/6393905/output.pdf) that clearly specifies or highlights the difference between source and target PDF files. And we used the same code as you shared earlier. 
The good thing is you can avail a temporary license [here](https://purchase.groupdocs.com/temporary-license) in order to avoid this evaluation limitation.

**Comment by poonamBattulwar** [comment]
Hi,

I tried using the temporary license as well, however its giving the same error. Can we arrange for a call?

Regards,
Poonam

**Comment by atirtahirgroupdocs** [comment]
@poonamBattulwar 

After applying the temporary license, you are still getting the evaluation message in the resultant PDF? 
It seems that the license is not properly applied or loaded. Please have a look at this [screencast.zip](https://github.com/groupdocs-free-consulting/projects/files/6399488/screencast.zip). You can add a breakpoint/debug and check if the license was properly applied. If issue persists, we'd recommend you to raise it on our free support [forum](http://forum.groupdocs.com/) or share your email address and we'll create a thread on your behalf.

**Comment by shahzad-latif** [comment]
@poonamBattulwar 

This issue will be further handled at [GroupDocs Free Forums](http://forum.groupdocs.com/). I'm closing this thread. Please do not reply here. Thanks.
