### ISSUE TITLE
groupdocs for docx TOC content extract

### ISSUE THREAD

**Issue by softkumsh** [groupdocs-free-consulting/projects#17]
We have some requirements to read the docx word document toc content. our use case needs to read the TOC content by giving the toc.
I am trying to do that with groupdocs parser , using the evolution version I can read two TOC item.I do have few other requirement need to address.
Wanted to know more about that before going for on licencing. Please provide the point of contact to reach out for this.

**Comment by atirtahirgroupdocs** [comment]
@softkumsh 

> using the evolution version

Please have a look a the API evaluation [limitations](https://docs.groupdocs.com/parser/net/evaluation-limitations-and-licensing/). 

> I do have few other requirement need to address.

Please let us know. However, we'd encourage you to raise or post your queries on free support [forum](https://forum.groupdocs.com/c/parser/17).

**Comment by softkumsh** [comment]
Is that possible to extract on every level of the TOC content (like TOC 1.2 contect ).

**Comment by atirtahirgroupdocs** [comment]
> We have some requirements to read the docx word document toc content. our use case needs to read the TOC content by giving the toc.
> I am trying to do that with groupdocs parser , using the evolution version I can read two TOC item.I do have few other requirement need to address.
> Wanted to know more about that before going for on licencing. Please provide the point of contact to reach out for this.

We already answered it on forum. Please have a look at this [thread](https://forum.groupdocs.com/t/parsing-images-and-tables-from-a-document-using-java/10002/7).


> Is that possible to extract on every level of the TOC content (like TOC 1.2 contect ).

This query is also assisted [here](https://forum.groupdocs.com/t/how-to-extract-data-on-every-level-of-the-toc-in-java/10015) on the forum.
