### ISSUE TITLE
Need guidance on loading images/pdfs using group docs and allowing the user to redact before saving them back 

### ISSUE THREAD

**Issue by krismukku** [groupdocs-free-consulting/projects#21]
Hi There,

We have a requirement wherein some of the pre-uploaded files need to be programmatically loaded in a viewer so the user can review and redact any sensitive information before saving it back. We have been reviewing the documentation for annotation control but cannot find any guidance on how we can programmatically pass a file id to the angular component and make it load. The current samples expect a file upload button to be clicked and it loads all documents from the samples folder and selecting one of the files from that list gets loaded in the viewer. Is there a way to bypass that step and directly load a file that is passed from the web form.  We cannot find a way to pass any value without modifying the angular component. Any help is greatly appreciated.

I can be reached at kmukku@cma.com

**Comment by atirtahirgroupdocs** [comment]
@krismukku 

We are investigating this scenario. Please spare us some time and we'll update you.

**Comment by atirtahirgroupdocs** [comment]
@krismukku 

> Is there a way to bypass that step and directly load a file that is passed from the web form. 

Currently, this feature is not supported. However, we'll implement it. Please keep track of this GitHub [issue](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET/issues/99). However, we'd recommend you to post such issues on our free support [forum](https://forum.groupdocs.com/).
