### ISSUE TITLE
Converting process from C# to .NET

### ISSUE THREAD

**Issue by astouffer23** [groupdocs-free-consulting/projects#22]
I wrote a process to crawl through a shared file repo,locate all pdf,xls,xlsx,dwg files and merge them into one master pdf.

The process works as intended in C#. Example would be 3 pdf documents (1.pdf, 2.pdf, 3.pdf)

![image](https://user-images.githubusercontent.com/24939179/167926678-3cd9f298-4e3d-4bdb-9654-65102299cd47.png)

This is not working in VB.NET. The end file that is output is only one page (the first page).

![image](https://user-images.githubusercontent.com/24939179/167926530-f090c178-8214-499c-ba1f-0a41358defda.png)

Apologies for the images and not the code, pasting code in here was not formatting correctly.

**Comment by astouffer23** [comment]
![image](https://user-images.githubusercontent.com/24939179/167930124-595a2c6d-8565-440f-aab9-3b7e67c386ce.png)

Removed some of the logic for clarity. This is not saving all files in final save.

**Comment by astouffer23** [comment]
![image](https://user-images.githubusercontent.com/24939179/167931607-cd892e68-61b4-4466-a940-d0b5aca67f05.png)
Another example of it not working in VB.NET.

**Comment by astouffer23** [comment]
I'm wondering if this is more of a licensing issue than anything, as the process works in the first app I developed and only returns one sheet in every application I have built after (through testing of this process).  

I created a new Windows Forms .NET C# solution with the same code that works in the first application, yet it also is only returning one page.

**Comment by atirtahirgroupdocs** [comment]
@astouffer23 

Do you see a [trial badge](https://docs.groupdocs.com/merger/net/licensing-and-subscription/#free-trial) or evaluation limitation mark on the generated/output page? 
However, we'd recommend you to always post such issues on our free support [forum](http://forum.groupdocs.com/).

**Comment by astouffer23** [comment]
@atirtahirgroupdocs , thanks for the reply. Wasn't sure appropriate way to contact for trial use prior to purchase. Some companies have teams to assist with config during that time.

No trial badge or eval mark.
[1111.5in thick anodize clip_80-20.pdf](https://github.com/groupdocs-free-consulting/projects/files/8678768/1111.5in.thick.anodize.clip_80-20.pdf)
above is what spits out when I attempt to run this process in any application aside from the first one I tested in, using the following code, which should have two pages:
![image](https://user-images.githubusercontent.com/24939179/168068742-8aed8a18-c4a0-43ea-bab1-a33fb68255f9.png)

**Comment by atirtahirgroupdocs** [comment]
@astouffer23 

> I created a new Windows Forms .NET C# solution with the same code that works in the first application, yet it also is only returning one page.

Could you please share a sample application using that issue could be reproduced?

**Comment by astouffer23** [comment]
@atirtahirgroupdocs 

I've attempted to upload, but running into file size limitations.

This is essentially the entire code. Even if I don't set license rights it still only spits out one page.

![image](https://user-images.githubusercontent.com/24939179/168091528-93aefb88-d795-4123-9a87-5c3e46c43726.png)

**Comment by astouffer23** [comment]
https://github.com/astouffer23/testMerge

**Comment by astouffer23** [comment]
I believe the issue is with release GroupDocs.Merger 22.4.0 FYI. Works as intended (both in C# and visual basic) when I roll back to 22.1.0.

**Comment by atirtahirgroupdocs** [comment]
@astouffer23 

This issue is reproduced at our end using latest API version. Therefore, we have logged it in our internal issue tracking system. You'll be notified in case of any update. 
In future, please create tickets/posts on our free support [forum](http://forum.groupdocs.com/).
Thanks

**Comment by atirtahirgroupdocs** [comment]
@astouffer23 

This issue is now fixed. Please try with API version [22.5](https://docs.groupdocs.com/merger/net/groupdocs-merger-for-net-22-5-release-notes/).
