### ISSUE TITLE
I want to simply view PDF in csharp WinForm using groupdoc nugget

### ISSUE THREAD

**Issue by olibara** [groupdocs-free-consulting/projects#25]
Please check if it satisfies the following requirements: 

* It is a small project satisfying a particular scenario
* It is related to GroupDocs APIs
* It takes 8 or less hours for us to complete
* It is not a bug
* It is not a feature request

If your requirement is actually a bug in our APIs or a feature request for our APIs then please use our forum to report it and get quick help: https://forum.groupdocs.com/

If all the above requirements are satisfied then please move on:

< describe your free consulting project requirements briefly>

< which platform you're working on -- operating system, development environment etc.> 

<attach input documents>

<attach any sample required output documents if you have> 

<attach any additional supporting material to help us understand the requirement>

**Comment by olibara** [comment]
I'm using .NET 4.6
The doc is not really explicit
I've tried this but it doesn't show anything

using (Viewer viewer = new Viewer("c:/tmp/RIT_Belcotex_4-3.pdf"))
      {
        // set PDF file security

        PdfViewOptions options = new PdfViewOptions();
        viewer.View(options);
      }
      So is groupdoc the right tools for that purpose (i do not want to convert, edit etc .. : simply view document )?

**Comment by vladimir-litvinchik** [comment]
@olibara 

Please take a look at our [WinForms Demo](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET/tree/master/Demos/WinForms). It is just a simple application that demonstrates basic Viewer capabilities.

The code you've provided loads PDF document and outputs PDF document without any changes. You can think of GroupDocs.Viewer as of a function that accepts a file on the input and produces the output in a desired format PNG/JPEG/HTML/PDF.

Please let us know if you have any questions and we'll try to assist you.

**Comment by olibara** [comment]
Thanks a lot

 

Therefore it is more a converter than a viewer

 

I will use something more light as PdfiumViewer

**Comment by vladimir-litvinchik** [comment]
@olibara 

You're welcome!
