### ISSUE TITLE
online demo compare can find differences while java dose not, what should I do ?

### ISSUE THREAD

**Issue by woxiangbo** [groupdocs-free-consulting/projects#34]
There are 2 excel files,  a.xls  and a2.xls
your online compare demo can find the differences  ( https://products.groupdocs.app/comparison/total )

but when compared the 2 files by java code,  the  ChangeInfo list's size is **ZERO**

why your online  demo and my code got different compare result ?
the 2 xls file have been uploaded
following is my code:
```
  try (Comparer comparer = new Comparer(new FileInputStream("E:\\pdf\\a.xls"))) {
            comparer.add(new FileInputStream("E:\\pdf\\a2.xls"));
            comparer.compare();
            ChangeInfo[] list  = comparer.getChanges();
            System.out.println(list.length);
        }
```

```
<dependencies>
        <dependency>
            <groupId>com.groupdocs</groupId>
            <artifactId>groupdocs-comparison</artifactId>
            <version>23.1</version>
        </dependency>
    </dependencies>
```

![c](https://user-images.githubusercontent.com/3446874/216524033-c610beb2-d8eb-4942-8149-df2c94646d11.png)
[a.xls](https://github.com/groupdocs-free-consulting/projects/files/10575977/a.xls)
[a2.xls](https://github.com/groupdocs-free-consulting/projects/files/10575978/a2.xls)

**Comment by atirtahirgroupdocs** [comment]
@woxiangbo 

We cannot reproduce this issue at our end. Please take a look at this screenshot

![screenshot](https://user-images.githubusercontent.com/15940608/216605443-6c26e62a-85da-4e22-b8dc-08517154b9f1.png)

You can see `ChangeInfo[]` length is 3. 
It seems you are evaluating the API without a license (we get 0 length in [trial mode](https://docs.groupdocs.com/comparison/java/evaluation-limitations-and-licensing-of-groupdocs-comparison/#evaluation-limitations)). Please avail a [temporary license](https://purchase.groupdocs.com/temporary-license/) and try the app again. A temporary license is time restricted full license. You may follow these [steps](https://kb.groupdocs.com/total/net/how-to-get-a-temporary-license-for-groupdocs/) to get temporary license.
