### ISSUE TITLE
Creating a standalone viewer.

### ISSUE THREAD

**Issue by danish-nix** [groupdocs-free-consulting/projects#35]
Hello, may I know if there is a standalove viewer which does not include calling from controller?

**Comment by atirtahirgroupdocs** [comment]
@danish-nix 

Please note that GroupDocs.Viewer is a back-end API that could be implemented in any (.NET or Java) application without framework (e.g. MVC, WebForms) dependency. 
You can explore our Web Forms, Windows Forms, WPF or .NET core [applications](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET/tree/master/Demos). 
The core purpose of the API is to render the [source file](https://docs.groupdocs.com/viewer/net/supported-document-formats/) to [PDF, Image or HTML](https://docs.groupdocs.com/viewer/net/rendering-documents/) files. Later, you can develop your own logic/UI to display the output (previously rendered PDF, Image or HTML) in browser or other applications (e.g. WPF, Windows Forms).
Given below is the basic code to render a Word file to PDF:

```
using (Viewer viewer = new Viewer("sample.docx"))
{
	// Create a PDF file.
	PdfViewOptions viewOptions = new PdfViewOptions();
	viewer.View(viewOptions);
}
```
Once rendered/converted, it's up to you how you want to display the PDF in browser or other applications. 
Same is the case with image and HTML renderings. Below is the code to render a Word file to HTML:

```
using (Viewer viewer = new Viewer("sample.docx"))
{
    // Create an HTML file.
    var viewOptions = HtmlViewOptions.ForExternalResources();
    viewer.View(viewOptions);
}
```
