### ISSUE TITLE
I want to build a normal document rendering functionality into our desktop application

### ISSUE THREAD

**Issue by Abhishek1385** [groupdocs-free-consulting/projects#4]
Hi,
I'm getting an error while using the Compare Single document function.
Exception : Exception while calling API: AmazonS3 Storage exception: The specified key does not exist. Bucket 'gfc-filestorage', FilePath '40894/97cb4bf1-fec1-46e3-b0de-be0bccdd5b99/Comparisondocs/source_protected.docx'

But i have not configured any Amazon S3 bucket in this, I'm still using the free storage option provided by Groupdocs. However the documents are uploaded there for comparing but still no luck.
I hope you guys can help here.

And I'm using the python SDK.

**Comment by shahzad-latif** [comment]
@Abhishek1385 

I'm sorry to know that you had to face this issue. 

Could you please post your query in our support forum, so our team can guide you appropriately? https://forum.groupdocs.cloud/

This space is reserved for free consulting projects only. You'll be better able to get quick answers for such questions in our forums. Thanks for your understanding.
