### ISSUE TITLE
I want to create/build 

### ISSUE THREAD

**Issue by karlenglund** [groupdocs-free-consulting/projects#41]
I have a page where I need a button to print Invoices.

This page is a PHP Laravel backend

I have two date controls to allow selection of a date range.   I have code that first selects all customers that have invoices in that date range.   Then the code does a MySQL query to select the line item data needed for the invoices.  The line item data also inclueds mailing information for mail merge purposes.  That query needs to send the data to an excel file.

I need code that will perform a mail merge using the results of the second query's excel file and perform a mail merge with a MicroSoft Word Mail merge document and output the results to PDF or email  for each customer found, one by one 

it is a Linux System, Laravel

[InvoiceSummaryWorking.docx](https://github.com/groupdocs-free-consulting/projects/files/12064860/InvoiceSummaryWorking.docx)
[InvoiceSCSSHeader.xlsx](https://github.com/groupdocs-free-consulting/projects/files/12064864/InvoiceSCSSHeader.xlsx)

**Comment by AlexNosk** [comment]
@karlenglund You can use Aspose.Words to execute mail merge. Please see our documentation to learn more:
<https://docs.aspose.com/words/net/mail-merge-and-reporting/>
Also, using Aspose.Words you can save the result in [various output formats](https://docs.aspose.com/words/net/supported-document-formats/) including PDF:
<https://docs.aspose.com/words/net/convert-a-document-to-pdf/>
