### ISSUE TITLE
Want to create/build API link for view or convert .j2k file, for our web based portal 

### ISSUE THREAD

**Issue by jayanta-iimi** [groupdocs-free-consulting/projects#7]
This is in reference to your portal “https://www.groupdocs.app/” for file viewing online, we have checked the .j2k image format file is opening and converting smoothly. 

So, in association with this we are looking for API link for our web base application to view/convert all our files from “.j2k” format. We are ready to discuss on that topic for more detailed information.

We would look forward to hearing from you as fast as possible.

**Comment by atirtahirgroupdocs** [comment]
@jayanta-iimi 

> we are looking for API link for our web base application to view/convert all our files from “.j2k” format

GroupDocs.Viewer API supports .j2k file format. API comes for both [.NET](https://products.groupdocs.com/viewer/net) and [Java](https://products.groupdocs.com/viewer/java) platforms. Can you please specify your development environment (.NET or Java) and we'll assist you accordingly. 

> This is in reference to your portal “https://www.groupdocs.app/” for file viewing online
This web application is using .NET variant of the API.
