### ISSUE TITLE
How to integrate Groupdocs viewer in .Net core and View the document in Angular 7

### ISSUE THREAD

**Issue by SriAzureDev** [groupdocs-free-consulting/projects#8]
Hi,

I have a requirement that i have document stream in Sql sever and using WebAPI i will be retrieving from the database and would like to pass that stream to Angular UI in order to display in the browser. I looked at the solutions which has been provided but I could not able to understand how to display them in UI using Angular 7. It would be great if you can provide us the sample solution, so that we can try to purchase to license and integrate the same in our application. Awaiting for you'r reply/

**Comment by atirtahirgroupdocs** [comment]
@SriAzureDev 

Please explore this basic demo project - [viewer_angular.zip](https://github.com/groupdocs-free-consulting/projects/files/5151813/viewer_angular.zip).

**A quick overview**

1. PageController.cs - the API controller that returns page content (it takes a stream/byte[] as input, renders it to HTML view and return output stream)
2. home.component.ts - component code
3. home.component.html - component markup

You can further look at [groupdocs.examples.angular](https://www.npmjs.com/package/@groupdocs.examples.angular/viewer) npm (a simple Angular app that allows you to display documents) and here's [how to use](https://gist.github.com/bobkovalex/0674e7d7c54a54daf01a37927df27b05) it.

**Comment by SriAzureDev** [comment]
Hi, 

I had looked at the code and one quick question, does it always should be viewed from iframe? so how does the <gd-viewer/> works in Angular, it would be great if you can provide me a solution with using gd-viewer.

**Comment by atirtahirgroupdocs** [comment]
@SriAzureDev 

It depends on what output format (e.g. PDF, Image, HTML) you're going to convert source file. When the output format is HTML then the simplest way would be embedding each page in the iframe as it enables you to embed complete HTML document. When the output format is JPEG or PNG you can use img tag.

>  so how does the works in Angular

Here is a working [example](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC). It uses https://www.npmjs.com/package/@groupdocs.examples.angular/viewer.

**Comment by shahzad-latif** [comment]
The related project can be viewed here [Display documents from a MemoryStream in ASP.NET MVC/.NET Core](https://github.com/groupdocs-free-consulting/display-document-in-browser-without-downloading)

**Comment by Framework-Support** [comment]
Hi Team,

To the above angular project, I am looking out for an example with Angular having options of Search, View, Merge, download, navigate , add comments, print. It would be great if you can provide me such example. As the example with angular is little confusing from the groupdocs total angular.

It is an urgent requirement and based on that we would like purchase the license asap.

**Comment by atirtahirgroupdocs** [comment]
@Framework-Support 
We have assisted this query on [forum](https://forum.groupdocs.com/t/search-view-merge-download-navigate-add-comments-print-options/9043/2?u=atir_tahir). Please take a look.
